#Step 1

FROM node:18-alpine as build-step

WORKDIR /usr/src/app

COPY package.json .

RUN npm install

# COPY . .

EXPOSE 4200


CMD ["npm", "run", "start"]
# RUN npm run build

# Step 2

# FROM nginx:1.17.1-alpine


# COPY --from=build-step /dist/meancrudapp/index.html /usr/share/nginx/html 